"""empty message

Revision ID: 8f23e92e4982
Revises: 
Create Date: 2023-12-14 20:24:49.391075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f23e92e4982'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pessoa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('sobrenome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('tb_arcondicionado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fabricante', sa.String(length=255), nullable=False),
    sa.Column('marca', sa.String(length=255), nullable=False),
    sa.Column('modelo', sa.String(length=255), nullable=False),
    sa.Column('numero_serie', sa.String(length=255), nullable=False),
    sa.Column('potencia', sa.Integer(), nullable=False),
    sa.Column('consumo', sa.Float(), nullable=False),
    sa.Column('voltagem', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_professor',
    sa.Column('id_professor', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.String(length=255), nullable=True),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('sobrenome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('telefone', sa.String(length=255), nullable=False),
    sa.Column('titulacao', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_professor'),
    sa.UniqueConstraint('matricula')
    )
    op.create_table('tb_tecnico_administrativo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('telefone', sa.String(length=255), nullable=False),
    sa.Column('cargo', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_coped',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tecnicoAdministrativo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tecnicoAdministrativo_id'], ['tb_tecnico_administrativo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_sala',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_bloco', sa.Integer(), nullable=False),
    sa.Column('capacidade', sa.Integer(), nullable=False),
    sa.Column('tipo_sala', sa.String(length=255), nullable=False),
    sa.Column('coped_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['coped_id'], ['tb_coped.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_aula',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inicio', sa.DateTime(), nullable=False),
    sa.Column('fim', sa.DateTime(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('sala_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['professor_id'], ['tb_professor.id_professor'], ),
    sa.ForeignKeyConstraint(['sala_id'], ['tb_sala.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_aula')
    op.drop_table('tb_sala')
    op.drop_table('tb_coped')
    op.drop_table('tb_tecnico_administrativo')
    op.drop_table('tb_professor')
    op.drop_table('tb_arcondicionado')
    op.drop_table('pessoa')
    # ### end Alembic commands ###
